# yazi.toml
[manager]
show_hidden = true

[opener]
edit = [
	{ run = "nvim %*",   block = true, for = "windows" },
]
play = [
	{ run = '"C:\Program Files\VideoLAN\VLC\vlc.exe" %*', orphan = true, for = "windows" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
